package mcpregister

import (
	// register hosted mcp
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/12306"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/aiproxy-openapi"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/amap"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/baidu-map"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/bingcn"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/cloudflare"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/context7"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/fetch"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/figma"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/firecrawl"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/flomo"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/gezhe"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/gitee"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/github"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/gpt-vis"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/hefeng-weather"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/howtocook"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/jina-tools"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/kuaidi100"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/microsoftdocs"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/nothon"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/screenshotone"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/semgrep"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/tavily"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/time"
	_ "github.com/wavespeed/llm-server/mcp-servers/hosted/web-search"
)
